#!/usr/bin/env bash
#
# Verifies that the package published on nuget.org is the package this repository builds.
#
# Why this is not a byte comparison of the two .nupkg files:
#
#   nuget.org applies its own *repository signature* on ingestion. That adds a
#   .signature.p7s entry to the archive and rewrites central-directory offsets, so the
#   published archive can never be byte-identical to a local build even when every file
#   inside is the same. Comparing whole archives reports a failure that is not one.
#
# And why it waits rather than checking immediately:
#
#   the signature is applied asynchronously after the package becomes downloadable. A
#   check that runs too early can download the unsigned copy and pass for the wrong
#   reason - which is how an earlier release "verified" successfully by accident.
#
# So: compare the archives entry by entry, on content, ignoring the signature entry, and
# only after the signature is present.
#
# Usage:
#   scripts/verify-published-package.sh <version> [--allow-unsigned]
#
# Example:
#   scripts/verify-published-package.sh 5.0.0
#
set -euo pipefail

VERSION="${1:-}"
ALLOW_UNSIGNED="${2:-}"

if [[ -z "$VERSION" ]]; then
    printf 'usage: %s <version> [--allow-unsigned]\n' "$0" >&2
    exit 2
fi

PACKAGE_ID='SYT.RozetkaPay'
LOWER_ID='syt.rozetkapay'
REPO_ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

fail() { printf '  FAIL  %s\n' "$1" >&2; exit 1; }
note() { printf '  ok    %s\n' "$1"; }

printf '[1/4] Downloading %s %s from nuget.org\n' "$PACKAGE_ID" "$VERSION"
URL="https://api.nuget.org/v3-flatcontainer/${LOWER_ID}/${VERSION}/${LOWER_ID}.${VERSION}.nupkg"
if ! curl -fsSL "$URL" -o "$WORK/published.nupkg"; then
    fail "not downloadable: $URL"
fi
note "downloaded $(wc -c <"$WORK/published.nupkg" | tr -d ' ') bytes"

printf '[2/4] Checking the repository signature is present\n'
# NOT 'unzip -l | grep -q': grep exits on the first match, unzip takes SIGPIPE, and under
# 'set -o pipefail' the pipeline then reports failure — turning a signature that IS present into
# "not present", non-deterministically depending on buffering. Materialise the listing first.
unzip -l "$WORK/published.nupkg" >"$WORK/published.listing"
if grep -q '\.signature\.p7s' "$WORK/published.listing"; then
    note 'repository signature present'
elif [[ "$ALLOW_UNSIGNED" == '--allow-unsigned' ]]; then
    printf '  warn  no signature yet; continuing because --allow-unsigned was passed\n'
else
    fail 'no .signature.p7s yet - nuget.org has not finished signing. Re-run in a minute, or
        pass --allow-unsigned to compare the unsigned copy deliberately.'
fi

printf '[3/4] Building the same version locally\n'
# Version is NOT overridden: MinVer derives it from the tag, and it also feeds
# InformationalVersion and the nuspec. Passing -p:Version bypasses MinVer, which produces a
# genuinely different assembly and nuspec — the check would then report differences it caused
# itself. The tag must be checked out for this to yield the version being verified.
dotnet pack "$REPO_ROOT/src/SYT.RozetkaPay/SYT.RozetkaPay.csproj" \
    -c Release -o "$WORK/local" \
    -p:ContinuousIntegrationBuild=true \
    --nologo -v q >"$WORK/pack.log" 2>&1 || { cat "$WORK/pack.log" >&2; fail 'dotnet pack failed'; }

LOCAL="$WORK/local/${PACKAGE_ID}.${VERSION}.nupkg"
if [[ ! -f "$LOCAL" ]]; then
    fail "local pack produced $(cd "$WORK/local" && ls ./*.nupkg 2>/dev/null | tr '\n' ' ')instead of
        ${PACKAGE_ID}.${VERSION}.nupkg. MinVer derives the version from the checked-out commit, so
        verify a version by checking out its tag first: git checkout v${VERSION}"
fi
note 'local package built'

printf '[4/4] Comparing published against local\n'
mkdir -p "$WORK/x-published" "$WORK/x-local"
unzip -qq "$WORK/published.nupkg" -d "$WORK/x-published"
unzip -qq "$LOCAL" -d "$WORK/x-local"

# Entries nuget.org adds on ingestion.
IGNORED='.signature.p7s'

# OPC core-properties carry a GUID in the file *name*, freshly generated by every 'dotnet pack', and
# _rels/.rels points at that name. Both therefore differ between any two builds of identical content.
list_entries() {
    (cd "$1" && find . -type f | sed 's|^\./||' \
        | grep -Fxv "$IGNORED" \
        | grep -v '^package/services/metadata/core-properties/.*\.psmdcp$' \
        | sort)
}

list_entries "$WORK/x-published" >"$WORK/entries-published"
list_entries "$WORK/x-local" >"$WORK/entries-local"

if ! diff -u "$WORK/entries-local" "$WORK/entries-published" >"$WORK/entries.diff"; then
    cat "$WORK/entries.diff" >&2
    fail 'entry lists differ (left: local, right: published)'
fi
note "$(wc -l <"$WORK/entries-local" | tr -d ' ') entries, same set"

# --- nuspec: identity and provenance -----------------------------------------------------------
#
# 'branch' is deliberately not compared. The release workflow builds a detached checkout of the tag,
# so SourceLink has no branch to record; a local build on main does. That is a fact about how the
# build was checked out, not about what shipped. The commit is what pins provenance, and it is
# compared exactly.
nuspec_field() {
    python3 - "$1" "$2" <<'PYEOF'
import re, sys
text = open(sys.argv[1], encoding='utf-8').read()
match = re.search(sys.argv[2], text)
print(match.group(1) if match else '')
PYEOF
}

for field in '<id>([^<]+)</id>' '<version>([^<]+)</version>' 'commit="([0-9a-f]{40})"'; do
    local_value="$(nuspec_field "$WORK/x-local/${PACKAGE_ID}.nuspec" "$field")"
    published_value="$(nuspec_field "$WORK/x-published/${PACKAGE_ID}.nuspec" "$field")"
    [[ -n "$local_value" ]] || fail "local nuspec has no match for $field"
    [[ "$local_value" == "$published_value" ]] \
        || fail "nuspec $field differs: local '$local_value' vs published '$published_value'"
done
note "nuspec id, version and repository commit identical"

# --- assembly: version and commit as compiled in --------------------------------------------------
#
# AssemblyInformationalVersion is '<version>+<commit>', written by MinVer and SourceLink. Comparing it
# proves the published binary was built from this version of this commit — which is the claim that
# matters to a consumer.
informational_version() {
    python3 - "$1" <<'PYEOF'
import re, sys
data = open(sys.argv[1], 'rb').read().decode('utf-8', errors='ignore')
found = sorted(set(re.findall(r'\d+\.\d+\.\d+(?:-[0-9A-Za-z.]+)?\+[0-9a-f]{40}', data)))
print(found[0] if len(found) == 1 else '|'.join(found))
PYEOF
}

DLL='lib/net10.0/SYT.RozetkaPay.dll'
LOCAL_IV="$(informational_version "$WORK/x-local/$DLL")"
PUBLISHED_IV="$(informational_version "$WORK/x-published/$DLL")"
[[ -n "$LOCAL_IV" ]] || fail 'no informational version found in the local assembly'
[[ "$LOCAL_IV" == "$PUBLISHED_IV" ]] \
    || fail "assembly informational version differs: local '$LOCAL_IV' vs published '$PUBLISHED_IV'"
note "assembly informational version identical ($LOCAL_IV)"

# --- optional: byte identity ----------------------------------------------------------------------
#
# Off by default, and that is a deliberate limitation rather than laziness. A deterministic build
# reproduces byte-for-byte only on the same toolchain: the compiler hashes its inputs into the PE
# timestamp and the MVID, so a local macOS SDK and the Linux runner differ in ~72 bytes of an
# otherwise identical 380 KB assembly. Claiming byte identity from a developer machine would either
# fail for the wrong reason or force an exemption wide enough to hide a real difference.
# Reproducibility itself is scripts/verify-deterministic-build.sh's job.
if [[ "${EXPECT_BYTE_IDENTICAL:-}" == '1' ]]; then
    printf '      byte comparison requested (EXPECT_BYTE_IDENTICAL=1)\n'
    DIFFERING=0
    while IFS= read -r entry; do
        if ! cmp -s "$WORK/x-local/$entry" "$WORK/x-published/$entry"; then
            printf '  diff  %s\n' "$entry" >&2
            DIFFERING=$((DIFFERING + 1))
        fi
    done <"$WORK/entries-local"
    [[ "$DIFFERING" -eq 0 ]] || fail "$DIFFERING entr(ies) differ byte-for-byte"
    note 'every entry byte-identical'
fi

printf '\nPASS  published %s %s is this repository at commit %s\n' \
    "$PACKAGE_ID" "$VERSION" "$(nuspec_field "$WORK/x-published/${PACKAGE_ID}.nuspec" 'commit="([0-9a-f]{40})"')"
